### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by foxkumar** [arminkz/TORPi#3]
Everything goes fine. I am able to see the network appearing in wifi search. However, once i get connected to the TorPi network, it does not work. 
![Capture](https://user-images.githubusercontent.com/70167132/91166582-7b061580-e6ca-11ea-8635-0a8f26cfd0c7.PNG)

**Comment by foxkumar** [comment]
Forgot to add one more screen shot
![Capture1](https://user-images.githubusercontent.com/70167132/91168005-c7eaeb80-e6cc-11ea-966f-2233ca6137de.PNG)

**Comment by arminkz** [comment]
there is a problem with Tor service. please check '/var/log/tor/notices.log' and send the error log.
